cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/CalloutData__c.object-meta.xml
<CustomObject>
    <label>CalloutData</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalloutData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/AuthenticationURL__c.field-meta.xml
<CustomField>
    <fullName>AuthenticationURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AuthenticationURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EndPointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/Integration_Configuration__mdt/Integration_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>IntegrationConfiguration</label>
    <pluralLabel>IntegrationConfigurations</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/Integration_Configuration__mdt/fields/API_Environment__c.field-meta.xml
<CustomField>
    <fullName>API_Environment__c</fullName>
    <description>API Environment like Dev QA or PROD</description>
    <inlineHelpText>API Environment like Dev QA or PROD</inlineHelpText>
    <label>API Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/OECCallOuts__mdt.object-meta.xml
<CustomObject>
    <label>OECCallOut</label>
    <pluralLabel>OECCallOuts</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevAccountId__c.field-meta.xml
<CustomField>
    <fullName>DevAccountId__c</fullName>
    <description>Stage Environment Account Id for API</description>
    <inlineHelpText>Stage Environment Account Id for API</inlineHelpText>
    <label>StageAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevAuthURL__c.field-meta.xml
<CustomField>
    <fullName>DevAuthURL__c</fullName>
    <description>Stage Environment Authentication URL</description>
    <inlineHelpText>Stage Environment Authentication URL</inlineHelpText>
    <label>StageAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>DevEndpointURL__c</fullName>
    <description>Stage Environment Endpoint URL</description>
    <inlineHelpText>Stage Environment Endpoint URL</inlineHelpText>
    <label>StageEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevPassword__c.field-meta.xml
<CustomField>
    <fullName>DevPassword__c</fullName>
    <description>Stage Environment User Password</description>
    <inlineHelpText>Stage Environment User Password</inlineHelpText>
    <label>StagePassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevUserName__c.field-meta.xml
<CustomField>
    <fullName>DevUserName__c</fullName>
    <description>Stage Environment User Name</description>
    <inlineHelpText>Stage Environment User Name</inlineHelpText>
    <label>StageUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdAccountId__c.field-meta.xml
<CustomField>
    <fullName>ProdAccountId__c</fullName>
    <description>Production Environment Account Id for API</description>
    <inlineHelpText>Production Environment Account Id for API</inlineHelpText>
    <label>ProdAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdAuthURL__c.field-meta.xml
<CustomField>
    <fullName>ProdAuthURL__c</fullName>
    <description>Production Environment Authentication URL</description>
    <inlineHelpText>Production Environment Authentication URL</inlineHelpText>
    <label>ProdAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>ProdEndpointURL__c</fullName>
    <description>Production Environment Endpoint URL</description>
    <inlineHelpText>Production Environment Endpoint URL</inlineHelpText>
    <label>ProdEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdPassword__c.field-meta.xml
<CustomField>
    <fullName>ProdPassword__c</fullName>
    <description>Production Environment User Password</description>
    <inlineHelpText>Production Environment User Password</inlineHelpText>
    <label>ProdPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdUserName__c.field-meta.xml
<CustomField>
    <fullName>ProdUserName__c</fullName>
    <description>Production Environment User Name</description>
    <inlineHelpText>Production Environment User Name</inlineHelpText>
    <label>ProdUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAAccountId__c.field-meta.xml
<CustomField>
    <fullName>QAAccountId__c</fullName>
    <description>QA Environment Account Id for API</description>
    <inlineHelpText>QA Environment Account Id for API</inlineHelpText>
    <label>QAAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAAuthURL__c.field-meta.xml
<CustomField>
    <fullName>QAAuthURL__c</fullName>
    <description>QA Environment Authentication URL</description>
    <inlineHelpText>QA Environment Authentication URL</inlineHelpText>
    <label>QAAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>QAEndpointURL__c</fullName>
    <description>QA Environment Endpoint URL</description>
    <inlineHelpText>QA Environment Endpoint URL</inlineHelpText>
    <label>QAEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAPassword__c.field-meta.xml
<CustomField>
    <fullName>QAPassword__c</fullName>
    <description>QA Environment User Password</description>
    <inlineHelpText>QA Environment User Password</inlineHelpText>
    <label>QAPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAUserName__c.field-meta.xml
<CustomField>
    <fullName>QAUserName__c</fullName>
    <description>QA Environment User Name</description>
    <inlineHelpText>QA Environment User Name</inlineHelpText>
    <label>QAUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/StandardTimeZone__mdt/StandardTimeZone__mdt.object-meta.xml
<CustomObject>
    <description>It holds all standard time zones</description>
    <label>StandardTimeZone</label>
    <pluralLabel>StandardTimeZone</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/StandardTimeZone__mdt/fields/TimeZone_Name__c.field-meta.xml
<CustomField>
    <fullName>TimeZone_Name__c</fullName>
    <label>TimeZone Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/TimeZoneConfiguration__mdt/TimeZoneConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>TimeZoneConfiguration</label>
    <pluralLabel>TimeZoneConfigurations</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/TimeZoneConfiguration__mdt/fields/TimeZoneType__c.field-meta.xml
<CustomField>
    <fullName>TimeZoneType__c</fullName>
    <label>TimeZoneType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>DaylightSaving</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/TimeZones__mdt/TimeZones__mdt.object-meta.xml
<CustomObject>
    <label>TimeZone</label>
    <pluralLabel>TimeZones</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/TimeZones__mdt/fields/TimeZone_Value__c.field-meta.xml
<CustomField>
    <fullName>TimeZone_Value__c</fullName>
    <label>TimeZone Value</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

cititechdNew2024Jan/force-app/main/default/classes/OECBatchOrderSyncHelper.cls
public class OECBatchOrderSyncHelper {


    String apiCalloutName = 'OECManualOrderCreation';
    String apiEnvironment;
    CalloutData__c cd;
    Cache.OrgPartition orgPart = Cache.Org.getPartition('local.StoreIDToken');
    Contact pm;
    Contact coPM;
    public CalloutData__c getCalloutData(){
        return cd;
    }
    public OECBatchOrderSyncHelper(){ 
    
        cd = loadCalloutParams();

    } 
    
    public void processOrders(List<Order> orders){

        String idToken = getAccessToken();
        if(String.isNotBlank(idToken)){
            for(Order ord : orders){
                if(validOrderToProcess(ord)){
                    syncOrder(idToken,ord);
                
                }
            
            }
        }
        else {
            System.debug('ID Token received from API is invalid hence closing');

        }

    }
    /**
    Finds the right Order needs to be synced back to OEC
    */
    public boolean validOrderToProcess(Order ord){
    
        System.debug(
            'ord.RecordType.Name:'+ Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname()+
            '- ord.CreatedBy.Name:'+ord.CreatedBy.Name+
            '- ord.Business_Line__c:'+ord.Business_Line__c+
            '- ord.Status:'+ord.Status+
            '- ord.Sync_to_OEC__c:'+ord.Sync_to_OEC__c+
            '- ord.Account.External_Sync__c'+ord.Account.External_Sync__c
        );
 
        if(Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() == 'Corporate_StreamLinks_Order' || 
                Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() == 'Corporate_Knovio_Order')
        {        

            return false;// We will not process Corporate_StreamLinks_Order orders
        }
        else if (ord.CreatedBy.Name == 'API Integration User') 
        {

            return false;// We will not process Order created by API Integration User
        }
        /*
        else if (ord.Business_Line__c != 'OE Connect' && 
                 ord.Business_Line__c != 'OE Conference' &&
                 ord.Business_Line__c != 'Corporate Services' ) 
        {

            return false; // We will not process any business line other than above
        } */
        else if (ord.Status != 'In Progress')
        {

            return false;
        }
        else if (ord.Sync_to_OEC__c == False)
        {

            return false;
        }
        else if(ord.Account.External_Sync__c != true)
        {

            return false;     
        }                
        return true;        
                    
    }
    
    private CalloutData__c loadCalloutParams(){
    
        Integration_Configuration__mdt ic = [SELECT API_Environment__c from Integration_Configuration__mdt];
        apiEnvironment = ic.API_Environment__c;
        
        System.debug('API Environment getting connected is -----> :'+apiEnvironment); 
        CalloutData__c cd;

        if (apiEnvironment == 'QA'){
            OECCallOuts__mdt callouts = [SELECT QAAccountId__c,QAAuthURL__c,QAEndpointURL__c,QAPassword__c,QAUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            cd = new CalloutData__c (AccountId__c=callouts.QAAccountId__c,AuthenticationURL__c=callouts.QAAuthURL__c,EndPointURL__c=callouts.QAEndpointURL__c,UserPassword__c=callouts.QAPassword__c,UserName__c=callouts.QAUserName__c);
        }
        else if (apiEnvironment == 'Prod'){
            OECCallOuts__mdt callouts = [SELECT ProdAccountId__c,ProdAuthURL__c,ProdEndpointURL__c,ProdPassword__c,ProdUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            cd = new CalloutData__c(AccountId__c=callouts.ProdAccountId__c,AuthenticationURL__c=callouts.ProdAuthURL__c,EndPointURL__c=callouts.ProdEndpointURL__c,UserPassword__c=callouts.ProdPassword__c,UserName__c=callouts.ProdUserName__c);
        }
        else {
            OECCallOuts__mdt callouts = [SELECT DevAccountId__c,DevAuthURL__c,DevEndpointURL__c,DevPassword__c,DevUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            cd = new CalloutData__c(AccountId__c=callouts.DevAccountId__c,AuthenticationURL__c=callouts.DevAuthURL__c,EndPointURL__c=callouts.DevEndpointURL__c,UserPassword__c=callouts.DevPassword__c,UserName__c=callouts.DevUserName__c);
        }
        return cd;
        
    }
    
    public String getAccessToken(){
           
       return getIDToken();       
       
    }
    private String getIDToken(){
   
        
        DateTime expiry = (DateTime)orgPart.get('expiry');
        String IDToken = (String)orgPart.get('IDToken');
        //System.debug('In getIDToken method ----------->> System.now():'+ system.now()+' - expiry date time:'+expiry+' - IDToken:'+IDToken); 
        //System.debug('Retrieved IDToken:'+IDToken+'-Expiry:'+expiry); 
        if (String.isNotBlank(IDToken) && (system.now() < expiry )){

            return IDToken;// returns the IDToken from platform cache
        
        }
        else {
            return getFreshToken();// returns the new token after fetchig        
        }
        
    }
    private void storeIdToken(String idTokenString){
        
        orgPart.put('IDToken',idTokenString);
        orgPart.put('expiry',system.now().addSeconds(3600));
    
    }
    private String getFreshToken(){
    

       String idTokenString;
       Http http = new Http();
       HttpRequest req = new HttpRequest();

       req.setEndpoint(cd.AuthenticationURL__c);
       req.setMethod('POST');
       
       Blob headerValue = Blob.valueof(cd.UserName__c+':'+cd.UserPassword__c);
        
       String authorizationValue = 'Basic '+EncodingUtil.base64Encode(headerValue);
       req.setHeader('Authorization',authorizationValue);
       
       System.debug('Req------------>>'+req);
       HttpResponse res = http.send(req);
       Order updateOrd = new Order();

       if (res.getStatusCode() == 200) 
       {
       
           //System.debug('Res------------->> '+res.toString());
           JSONParser jpar = JSON.createParser(res.getBody());
           //System.debug('jpar------------->>'+jpar);
           
           while(jpar.nextToken() != NULL){
               
               if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'idToken'){
                   jpar.nextToken();
                   idTokenString = jpar.getText();
                   //System.debug('idTokenString ------------->>'+idTokenString);
               }
                   
           }
           storeIdToken(idTokenString);
          
           return idTokenString; 
        }  
        else return null;
    
    }
    private void syncOrder(String idTokenString, Order ord){
       findProjectManagers(ord);
       //Map<String,TimeZones__mdt> tz = TimeZones__mdt.getAll(); 
       Http http = new Http();
       HttpRequest req = new HttpRequest();
       req.setEndpoint(cd.EndPointURL__c);
       req.setMethod('POST');
       
       req.setHeader('Content-Type', 'application/json');
       req.setHeader('X-OEX-SF-Account-ID', ord.AccountId);
       req.setHeader('X-OEX-Int-Account-ID', cd.AccountId__c);
       //req.setHeader('X-OEX-Int-Account-ID', ord.AccountId);
       req.setHeader('X-OEX-Int-Authorization',idTokenString);
    
       String ed = ord.End_Date_Time__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
       String sd = ord.Start_Date_Time__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
       
       String timeZoneValue = findTimeZoneValue(ord.Order_TimeZone__c);
       
       
       
       String body = '{'+
                      '"endDateTime":"'+ed+'",'+
                      '"oeNumber":"'+(ord.OrderNumber).replaceFirst( '^0+', '')+'",'+
                      '"name":"'+ord.OEC_Event_Name__c+'",'+                                      
                      '"startDateTime":"'+sd+'",'+
                      '"timeZone":"'+timeZoneValue+'",'+
                      '"type":"'+ord.Event_Type_OE_Defined__c+'",'+
                      '"orderId":"'+ ord.Id+'",';
                      
           if(String.isNotBlank(ord.Region__c) && (ord.Region__c == 'AMER' || ord.Region__c == 'APAC' || ord.Region__c == 'EMEA'))               
                      body = body+ '"region":"'+ord.Region__c+'",';  
                      
           if(String.isNotBlank(ord.Business_Line__c) && (ord.Business_Line__c != 'None')){
                      body = body+ '"businessLine":"'+ord.Business_Line__c+'"';  
           }            
           body = body+ addProjectManagers();                            
           body = body+'}';
                      
       String eventString ;
       String orderId;
       String eventId;
       String externalEventIdl;
       String errorMsg;
       boolean syncFailed = false;
       Order updateOrd;              
       System.debug('Body------------->> '+Body);
       req.setBody(body);
       HttpResponse res = http.send(req);
        
       System.debug('Res------------->> '+res.toString());
       JSONParser jpar = JSON.createParser(res.getBody());
       
       
       while(jpar.nextToken() != NULL){

           
           if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'eventLink'){
               jpar.nextToken();
               eventString = jpar.getText();
               System.debug('eventString ------------->>'+eventString);
           }
           if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'orderId'){
               jpar.nextToken();
               orderId = jpar.getText();
           }
           if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'eventId'){
               jpar.nextToken();
               eventId = jpar.getText();

           }
           if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'externalEventIdl'){
               jpar.nextToken();
               externalEventIdl = jpar.getText();
           }
           if((jpar.getCurrentToken() == JSONTOKEN.FIELD_NAME) && jpar.getText() == 'errorMessages'){
               jpar.nextToken();
               jpar.nextToken();
               errorMsg = jpar.getText();
               System.debug('errorMsg---------->>'+errorMsg);
               syncFailed = true;
            
           }

               
       }
       if(String.isNotBlank(eventString) && String.isNotBlank(orderId))// Sync success
       {
            updateSyncedOrder(orderId,eventString,eventId,externalEventIdl,ord);
       }
       else //if (syncFailed)
       {
           updateFailedOrder(ord,errorMsg);
       }   
       
       
        
    }

    public static String findTimeZoneValue(String tzn){
          
       String GMTTimezoneName = 'UTC';
      
       if(String.isNotBlank(tzn)){
           
           Map<String,TimeZones__mdt> dlsTZ ;
           Map<String,StandardTimeZone__mdt> standardTZ ;
        
           TimeZoneConfiguration__mdt tt = [SELECT TimeZoneType__c from TimeZoneConfiguration__mdt];
           String timeZoneType = tt.TimeZoneType__c;

           String timeZoneValue ;  
           //if (timeZoneType == 'DaylightSaving'){  // Irrespective of Time zone we need to send the Timezone value.
               dlsTZ = TimeZones__mdt.getAll();
               for(String timezoneName : dlsTZ.keySet()){
                    System.debug('dlsTZ.get(timezoneName).TimeZone_Name__c ----->>'+dlsTZ.get(timezoneName).TimeZone_Name__c);
                    if(dlsTZ.get(timezoneName).TimeZone_Name__c == tzn)
                        return dlsTZ.get(timezoneName).TimeZone_Value__c;
                                    
               }
           //}    
           
           //else{
               standardTZ = StandardTimeZone__mdt.getAll();
               for(String timezoneName : standardTZ.keySet()){
                    System.debug('standardTZ.get(timezoneName).TimeZone_Name__c ----->>'+standardTZ.get(timezoneName).TimeZone_Name__c);
                    if(standardTZ.get(timezoneName).TimeZone_Name__c == tzn)
                        return standardTZ.get(timezoneName).TimeZone_Value__c;
                                    
               }
           //}
      }
      return GMTTimezoneName;     
    }  
     
    private void updateSyncedOrder (String orderId, String eventString, String eventId, String externalEventId, Order ord){
    
           Decimal retryCount = ord.Sync_Retry_Count__c;     
           
           Order updateOrd =  [Select Id,OE_Central_URL__c,SyncStatus__c,Sync_Retry_Count__c,OECEventId__c,OECExternalEventId__c from Order where Id = :orderId];
           updateOrd.OE_Central_URL__c = eventString;
           updateOrd.SyncStatus__c='Synced';
           updateOrd.Sync_Datetime__c = System.now();
           updateOrd.OECEventId__c = eventId;
           updateOrd.OECExternalEventId__c = externalEventId;
           updateOrd.Sync_Retry_Count__c = retryCount+1;
           updateOrd.Sync_Error_Message__c='';

           update updateOrd;  
           
    }
    
    private void updateFailedOrder (Order ord, String errorMsg){
           

           order updateOrd =  [Select Id,Sync_Retry_Count__c,SyncStatus__c, Sync_Error_Message__c from Order where Id = :ord.Id];
           Decimal retryCount = updateOrd.Sync_Retry_Count__c;
 
           
           if (retryCount == 4)
               updateOrd.SyncStatus__c='Error'; 
               
           updateOrd.Sync_Error_Message__c=errorMsg;           
           updateOrd.Sync_Retry_Count__c = retryCount+1;
           update updateOrd; 

    
    }
    private void findProjectManagers(Order ord){
    
       if (String.isNotblank(ord.Project_Manager__c))  
           pm = [select email,FirstName,LastName from Contact where id = :ord.Project_Manager__c];
       if (String.isNotblank(ord.Project_Manager_2__c))    
           coPM = [select email,FirstName,LastName from Contact where id = :ord.Project_Manager_2__c];
       
       /*
       System.debug('pm.FirstName------------>>'+pm.FirstName);
       System.debug('pm.LastName------------>>'+pm.LastName);
       System.debug('pm.email------------>>'+pm.email);
    
    
       System.debug('coPM.FirstName------------>>'+coPM.FirstName);
       System.debug('coPM.LastName------------>>'+coPM.LastName);
       System.debug('coPM.email------------>>'+coPM.email);
       */ 
    }    
    private String addProjectManagers(){
        boolean pmExist = false;
        boolean copmExist = false;
        String managersBody ='';
        if( pm != null) {
            if (String.isNotblank(pm.email) || String.isNotblank(pm.LastName) || String.isNotblank(pm.FirstName)){
                pmExist = true;
            }  
        } 
        if(coPM != null) {
            if (String.isNotblank(coPM.email) || String.isNotblank(coPM.LastName) || String.isNotblank(coPM.FirstName)){
                copmExist = true;
            }
        }
        if(pmExist || copmExist){
            managersBody = ', "deliveryTeamMembers": [';
            
            if (pmExist){
                managersBody = managersBody + '{ "deliveryTeamMemberRole": "'+'PROJECT_MANAGER" ';
                if(String.isNotblank(pm.email))
                  managersBody = managersBody + ', "email": "'+pm.email+'"';
                if(String.isNotblank(pm.FirstName))
                  managersBody = managersBody + ', "firstName": "'+pm.FirstName+'"';
                if(String.isNotblank(pm.LastName))
                  managersBody = managersBody + ', "lastName": "'+pm.LastName+'"';  
            }
            if (pmExist && copmExist)
                managersBody = managersBody + '},';
            if (copmExist){
                managersBody = managersBody + '{ "deliveryTeamMemberRole": "'+'CO_PROJECT_MANAGER" ';
                if(String.isNotblank(coPM.email))
                  managersBody = managersBody + ', "email": "'+coPM.email+'"';
                if(String.isNotblank(coPM.FirstName))
                  managersBody = managersBody + ', "firstName": "'+coPM.FirstName+'"';
                if(String.isNotblank(coPM.LastName))
                  managersBody = managersBody + ', "lastName": "'+coPM.LastName+'"';  
            }
        }
        if (pmExist || copmExist)
            managersBody = managersBody +'}]';
        System.debug('managersBody------------------>>'+managersBody);
        return managersBody;
    }
    
}