cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/CalloutData__c.object-meta.xml
<CustomObject>
    <label>CalloutData</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CalloutData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/AuthenticationURL__c.field-meta.xml
<CustomField>
    <fullName>AuthenticationURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AuthenticationURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/CalloutData__c/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EndPointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/Integration_Configuration__mdt/Integration_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>IntegrationConfiguration</label>
    <pluralLabel>IntegrationConfigurations</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/Integration_Configuration__mdt/fields/API_Environment__c.field-meta.xml
<CustomField>
    <fullName>API_Environment__c</fullName>
    <description>API Environment like Dev QA or PROD</description>
    <inlineHelpText>API Environment like Dev QA or PROD</inlineHelpText>
    <label>API Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/OECCallOuts__mdt.object-meta.xml
<CustomObject>
    <label>OECCallOut</label>
    <pluralLabel>OECCallOuts</pluralLabel>
</CustomObject>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevAccountId__c.field-meta.xml
<CustomField>
    <fullName>DevAccountId__c</fullName>
    <description>Stage Environment Account Id for API</description>
    <inlineHelpText>Stage Environment Account Id for API</inlineHelpText>
    <label>StageAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevAuthURL__c.field-meta.xml
<CustomField>
    <fullName>DevAuthURL__c</fullName>
    <description>Stage Environment Authentication URL</description>
    <inlineHelpText>Stage Environment Authentication URL</inlineHelpText>
    <label>StageAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>DevEndpointURL__c</fullName>
    <description>Stage Environment Endpoint URL</description>
    <inlineHelpText>Stage Environment Endpoint URL</inlineHelpText>
    <label>StageEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevPassword__c.field-meta.xml
<CustomField>
    <fullName>DevPassword__c</fullName>
    <description>Stage Environment User Password</description>
    <inlineHelpText>Stage Environment User Password</inlineHelpText>
    <label>StagePassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/DevUserName__c.field-meta.xml
<CustomField>
    <fullName>DevUserName__c</fullName>
    <description>Stage Environment User Name</description>
    <inlineHelpText>Stage Environment User Name</inlineHelpText>
    <label>StageUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdAccountId__c.field-meta.xml
<CustomField>
    <fullName>ProdAccountId__c</fullName>
    <description>Production Environment Account Id for API</description>
    <inlineHelpText>Production Environment Account Id for API</inlineHelpText>
    <label>ProdAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdAuthURL__c.field-meta.xml
<CustomField>
    <fullName>ProdAuthURL__c</fullName>
    <description>Production Environment Authentication URL</description>
    <inlineHelpText>Production Environment Authentication URL</inlineHelpText>
    <label>ProdAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdCancelEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>ProdCancelEndpointURL__c</fullName>
    <label>ProdCancelEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>ProdEndpointURL__c</fullName>
    <description>Production Environment Endpoint URL</description>
    <inlineHelpText>Production Environment Endpoint URL</inlineHelpText>
    <label>ProdEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdPassword__c.field-meta.xml
<CustomField>
    <fullName>ProdPassword__c</fullName>
    <description>Production Environment User Password</description>
    <inlineHelpText>Production Environment User Password</inlineHelpText>
    <label>ProdPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdTeamsCreationEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>ProdTeamsCreationEndpointURL__c</fullName>
    <label>ProdTeamsCreationEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/ProdUserName__c.field-meta.xml
<CustomField>
    <fullName>ProdUserName__c</fullName>
    <description>Production Environment User Name</description>
    <inlineHelpText>Production Environment User Name</inlineHelpText>
    <label>ProdUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAAccountId__c.field-meta.xml
<CustomField>
    <fullName>QAAccountId__c</fullName>
    <description>QA Environment Account Id for API</description>
    <inlineHelpText>QA Environment Account Id for API</inlineHelpText>
    <label>QAAccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAAuthURL__c.field-meta.xml
<CustomField>
    <fullName>QAAuthURL__c</fullName>
    <description>QA Environment Authentication URL</description>
    <inlineHelpText>QA Environment Authentication URL</inlineHelpText>
    <label>QAAuthURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QACancelEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>QACancelEndpointURL__c</fullName>
    <label>QACancelEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>QAEndpointURL__c</fullName>
    <description>QA Environment Endpoint URL</description>
    <inlineHelpText>QA Environment Endpoint URL</inlineHelpText>
    <label>QAEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAPassword__c.field-meta.xml
<CustomField>
    <fullName>QAPassword__c</fullName>
    <description>QA Environment User Password</description>
    <inlineHelpText>QA Environment User Password</inlineHelpText>
    <label>QAPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QATeamsCreationEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>QATeamsCreationEndpointURL__c</fullName>
    <label>QATeamsCreationEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/QAUserName__c.field-meta.xml
<CustomField>
    <fullName>QAUserName__c</fullName>
    <description>QA Environment User Name</description>
    <inlineHelpText>QA Environment User Name</inlineHelpText>
    <label>QAUserName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/StageCancelEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>StageCancelEndpointURL__c</fullName>
    <label>StageCancelEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/objects/OECCallOuts__mdt/fields/StageTeamsCreationEndpointURL__c.field-meta.xml
<CustomField>
    <fullName>StageTeamsCreationEndpointURL__c</fullName>
    <label>StageTeamsCreationEndpointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

cititechdNew2024Jan/force-app/main/default/classes/OECSyncManualOrdersHelper.cls
public class OECSyncManualOrdersHelper {


    String apiCalloutName = 'OECManualOrderCreation';
    String apiEnvironment;
    CalloutData__c cd;
    CalloutData__c cancelledcd;
    CalloutData__c teamscd;

    private static Set<Id> alreadyProcessed = new Set<Id>();
    private static Set<Id> alreadyProcessedForTeams = new Set<Id>();
    private static Set<Id> alreadyProcessedForCancelledOrds = new Set<Id>();
    //private static Set<Id> alreadyProcessedOrds = new Set<Id>();
    Order[] ords;  
    public OECSyncManualOrdersHelper(list<Order> triggerNew,map<Id,Order> triggerNewmap){ 
    
        
        //Load required details for onAfter Insert 
        //IdOrderMapBatch=IdOrderMap;
        //getAccessToken(outBoundCallName);
       
        // Fetch environment variable from custom metadata
        // Fetch API Environment to be connected from custom meta data
        

           
        //Load custom settings for the current environment for the API.
        loadCalloutParams();
        ords = [SELECT teams_created__c, SyncStatus__c, recordtypeid, CreatedBy.Name , Business_Line__c, Status, 
               Sync_to_OEC__c, Project_Manager__c, Project_Manager_2__c, Account.External_Sync__c, RecordType.Name,OEC_Event_Name__c,name FROM Order WHERE Id IN :triggerNew and RecordType.Name in ('Standard Order','No Contract Required Order') ];
 
        System.debug('CalloutData__c---------------->>'+cd);
         
    } 

    public void onAfterUpdate(list<Order> triggerNew,map<Id,Order> triggerNewmap){
        
        Map<id,Order> IdOrderMap = new Map<Id,Order>();
        Map<id,Order> IdCanOrderMap = new Map<Id,Order>();
        Map<id,Order> IdTeamOrderMap = new Map<Id,Order>();
        //updateOECEventName();
        for(Order ord:ords){
            
            System.debug('In For loop---------------->>1');
            if(ord.Status == 'In Progress' && String.isBlank(ord.SyncStatus__c)){
                System.debug('In In Progress---------------->>2');
                if(validOrderToProcess(ord) && !alreadyProcessed.contains(ord.id)){
                    System.debug('In In Progress---------------->>1.2');
                    alreadyProcessed.add(ord.id);
                    IdOrderMap.put(ord.id,ord);
                }

            }
            if(ord.Status == 'In Progress' && (String.isNotBlank(ord.Project_Manager__c) || String.isNotBlank(ord.Project_Manager_2__c))){
                System.debug('In In Progress and not Blank of Project_Manager__c ---------------->>2.1');
                if(validOrderToProcessTeamsCreation(ord) && !alreadyProcessedForTeams.contains(ord.id)){
                //if(validOrderToProcessTeamsCreation(ord)){
                    System.debug('In In Progress and Project_Manager__c is Set ---------------->>2.2');
                    alreadyProcessedForTeams.add(ord.id);
                    IdTeamOrderMap.put(ord.id,ord);
                    System.debug('In In Progress and Project_Manager__c is Set ---------------->>2.3');
                    System.debug('IdTeamOrderMap Size  ---------------->>2.4: '+IdTeamOrderMap.size());
                }
            }  
            if((ord.Status == 'Cancelled'  || ord.status == 'Paid' || ord.status == 'Delivered' || ord.status == 'Ready to Bill' || ord.status == 'Invoice Sent') && !alreadyProcessedForCancelledOrds.contains(ord.id)){   
                System.debug('In IdOrderMap.size---------------->>3');
                alreadyProcessedForCancelledOrds.add(ord.id);
                IdCanOrderMap.put(ord.id,ord);
                // Erite new real time Sync to process the Cancelled Orders   
                
            } 
         } 
         System.debug('---------------->>2000:'+'System.isFuture() -'+System.isFuture()+'-System.isBatch():'+System.isBatch());
         //if(!System.isFuture() && !System.isBatch()){
             if(IdOrderMap.size() > 0){
             
                 System.debug('In IdOrderMap.size---------------->>4:'+IdOrderMap.size());
                 //database.executeBatch(new OECManualOrderSync(IdOrderMap, cd),1); // Calling batch class.
                 OECSyncManualOrdersFuture.callManualOrderSync(IdOrderMap.keySet());
                        
             }    
         
             if(IdCanOrderMap.size() > 0){
                 System.debug('In IdOrderMap.size---------------->>5:'+ IdCanOrderMap.size() );
                 //database.executeBatch(new OECOrderStatusSync(IdCanOrderMap, cancelledcd),1); // Calling batch class.  
                 System.enqueueJob(new OECOrderStatusSyncQueueble (IdCanOrderMap.keySet(),cancelledcd),1);
                                
             }
             
             if(IdTeamOrderMap.size() > 0){
                 System.debug('In IdTeamOrderMap.size---------------->>6:'+IdTeamOrderMap.size());
                 //database.executeBatch(new OECOrderTeamsSync(IdTeamOrderMap, teamscd),1); // Calling batch class.  
                 //OECBatchOrderSyncHelper2.callOrderTeamsCreationSync(IdOrderMap.keySet());    
                 System.enqueueJob(new OECOrderTeamsCreationQueueble(IdTeamOrderMap.keySet(), teamscd));                 
             }
         
        // }       
    }    
    
    public void onBeforeInsert(list<Order> triggerNew,map<Id,Order> triggerNewmap){
        
        List<Order> listOrders = new List<Order>();
        
        for(Order ord:triggerNew){

            if((String.isBlank(ord.OEC_Event_Name__c)) || ord.isClone()) 
                ord.OEC_Event_Name__c = ord.Name;

            listOrders.add(ord); 

        }
        
        if(listOrders.size() > 0){
            dupCheckonOECEventName(triggerNew);                
        }        
    }
    /*
    public void onBeforeUpdate(list<Order> triggerNew,map<Id,Order> triggerNewmap){
        
        List<Order> listOrders = new List<Order>();
        
        for(Order ord:triggerNew){

             if(ord.CreatedBy.Name == 'API Integration User' )
                ord.OEC_Event_Name__c = ord.Name;

            listOrders.add(ord); 

        }
        
        if(listOrders.size() > 0){
            dupCheckonOECEventName(triggerNew);                
        }        
    }   */ 
    
    /**
    Finds the right Order needs to be synced back to OEC
    */
    private boolean validOrderToProcess(Order ord){
    
    /*
        System.debug(
            'ord.RecordType.Name:'+ Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname()+
            '- ord.CreatedBy.Name:'+ord.CreatedBy.Name+
            '- ord.Business_Line__c:'+ord.Business_Line__c+
            '- ord.Status:'+ord.Status+
            '- ord.Sync_to_OEC__c:'+ord.Sync_to_OEC__c+
            '- ord.Account.External_Sync__c'+ord.Account.External_Sync__c
        );*/
        
        if (String.isNotBlank(ord.SyncStatus__c)){
            System.debug('Returning due to ------------>>  ord.SyncStatus__c');
            return false; 
            
        }    
        //else if(ord.RecordType.Name == 'Corporate_StreamLinks_Order' || ord.RecordType.Name == 'Corporate_Knovio_Order')
        else if(String.isBlank(ord.RecordType.Name )){
            System.debug('Returning due to ------------>>  ord.RecordType.Name ');
            return false;
        }
        else if(Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() != 'Standard Order' && 
                Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() != 'No Contract Required Order')
        {        
            System.debug('Returning due to ------------>>  ord.RecordType.ID ');
            return false;// We will not process Corporate_StreamLinks_Order orders
        }
        else if (ord.CreatedBy.Name == 'API Integration User') 
        {
            System.debug('Returning due to ------------>>  ord.CreatedBy.Name ');
            return false;// We will not process Order created by API Integration User
        }
        else if (ord.Status != 'In Progress')
        {
            System.debug('Returning due to Sync------------>>  ord.Status');
            return false;
        }
        else if (ord.Sync_to_OEC__c == False)
        {
            System.debug('Returning due to ------------>>  Sync_to_OEC__c');
            return false;
        }
        else if(ord.Account.External_Sync__c != true)
        {
            System.debug('Returning due to ------------>>  External_Sync__c ');
            return false;     
        }                
        return true;        
                    
    }
    
    /**
    Finds the right Order needs to be used to create Teams Group    
    */
    private boolean validOrderToProcessTeamsCreation(Order ord){
    
    /*
        System.debug( 'ord.RecordType.Name:'+ Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname()+
            '- ord.CreatedBy.Name:'+ord.CreatedBy.Name+
            '- ord.Business_Line__c:'+ord.Business_Line__c+
            '- ord.Status:'+ord.Status+
            '- ord.Sync_to_OEC__c:'+ord.Sync_to_OEC__c+
            '- ord.Account.External_Sync__c'+ord.Account.External_Sync__c
        );*/
        System.debug('------------------------>> 1000 -ord.Account.External_Sync__c :'+ ord.Account.External_Sync__c
                                                      + '-ord.Sync_to_OEC__c:'+ord.Sync_to_OEC__c
                                                      + '-ord.SyncStatus__c :'+ord.SyncStatus__c);
        /*
        if (String.isNotBlank(ord.SyncStatus__c)){
            System.debug('Returning due to Teams------------>>  ord.SyncStatus__c');
            return false; 
            
        }    
        else */
        if(String.isBlank(ord.RecordType.Name )){
            System.debug('Returning due to ------------>>  ord.RecordType.Name ');
            return false;
        }
        else if(Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() != 'Standard Order' && 
                Schema.SObjectType.Order.getRecordTypeInfosById().get(ord.recordtypeid).getname() != 'No Contract Required Order')
        {        
            System.debug('Returning due to ------------>>  ord.RecordType.ID ');
            return false;// We will not process Corporate_StreamLinks_Order orders
        }/*
        else if (ord.CreatedBy.Name == 'API Integration User') 
        {
            System.debug('Returning due to ------------>>  ord.CreatedBy.Name ');
            return false;// We will not process Order created by API Integration User
        }
        else if (ord.Status != 'In Progress')
        {
            System.debug('Returning due to ------------>>  ord.Status');
            return false;
        }
        else if (ord.Sync_to_OEC__c == False)
        {
            System.debug('Returning due to ------------>>  Sync_to_OEC__c');
            return false;
        }
        else if(ord.Account.External_Sync__c != true)
        {
            System.debug('Returning due to ------------>>  External_Sync__c ');
            return false;     
        }*/  
        else if (ord.teams_created__c != 'Pending')
        {
            System.debug('Returning due to ------------>>  teams_created__c not equal to Pending');
            return false;
        }
        else if(ord.Account.External_Sync__c == true && ord.Sync_to_OEC__c == true && 
            ( ord.SyncStatus__c != 'Failed' && ord.SyncStatus__c != 'Error' && ord.SyncStatus__c != 'Synced'))
        {
            System.debug('Returning due to ------------>>  Order enabled for Sync in Account as well as Order but OEC Sync not yet processed');
            return false;     
        }                
        return true;        
                    
    }
    private void loadCalloutParams(){
    
        Integration_Configuration__mdt ic = [SELECT API_Environment__c from Integration_Configuration__mdt];
        apiEnvironment = ic.API_Environment__c;
        
        System.debug('API Environment getting connected is -----> :'+apiEnvironment); 
        //CalloutData__c cd;

        if (apiEnvironment == 'QA'){
            OECCallOuts__mdt callouts = [SELECT QATeamsCreationEndpointURL__c, QACancelEndpointURL__c, QAAccountId__c,QAAuthURL__c,QAEndpointURL__c,QAPassword__c,QAUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            //OECCallOuts__mdt callouts = [SELECT QAAccountId__c,QAAuthURL__c,QAEndpointURL__c,QAPassword__c,QAUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            cd = new CalloutData__c (AccountId__c=callouts.QAAccountId__c,AuthenticationURL__c=callouts.QAAuthURL__c,EndPointURL__c=callouts.QAEndpointURL__c,UserPassword__c=callouts.QAPassword__c,UserName__c=callouts.QAUserName__c);
            teamscd = new CalloutData__c (AccountId__c=callouts.QAAccountId__c,AuthenticationURL__c=callouts.QAAuthURL__c,EndPointURL__c=callouts.QATeamsCreationEndpointURL__c,UserPassword__c=callouts.QAPassword__c,UserName__c=callouts.QAUserName__c);
            cancelledcd = new CalloutData__c (AccountId__c=callouts.QAAccountId__c,AuthenticationURL__c=callouts.QAAuthURL__c,EndPointURL__c=callouts.QACancelEndpointURL__c,UserPassword__c=callouts.QAPassword__c,UserName__c=callouts.QAUserName__c);
            
        }
        else if (apiEnvironment == 'Prod'){
            OECCallOuts__mdt callouts = [SELECT ProdTeamsCreationEndpointURL__c,ProdCancelEndpointURL__c, ProdAccountId__c,ProdAuthURL__c,ProdEndpointURL__c,ProdPassword__c,ProdUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            cd = new CalloutData__c(AccountId__c=callouts.ProdAccountId__c,AuthenticationURL__c=callouts.ProdAuthURL__c,EndPointURL__c=callouts.ProdEndpointURL__c,UserPassword__c=callouts.ProdPassword__c,UserName__c=callouts.ProdUserName__c);
            teamscd = new CalloutData__c (AccountId__c=callouts.ProdAccountId__c,AuthenticationURL__c=callouts.ProdAuthURL__c,EndPointURL__c=callouts.ProdTeamsCreationEndpointURL__c,UserPassword__c=callouts.ProdPassword__c,UserName__c=callouts.ProdUserName__c);
            cancelledcd = new CalloutData__c (AccountId__c=callouts.ProdAccountId__c,AuthenticationURL__c=callouts.ProdAuthURL__c,EndPointURL__c=callouts.ProdCancelEndpointURL__c,UserPassword__c=callouts.ProdPassword__c,UserName__c=callouts.ProdUserName__c);
        }
        else {
            
            OECCallOuts__mdt callouts = [SELECT StageTeamsCreationEndpointURL__c,StageCancelEndpointURL__c, DevAccountId__c,DevAuthURL__c,DevEndpointURL__c,DevPassword__c,DevUserName__c FROM OECCallOuts__mdt where Label ='OECManualOrderCreation'];
            System.debug('StageTeamsCreationEndpointURL__c----------->>'+callouts.StageTeamsCreationEndpointURL__c);
            cd = new CalloutData__c(AccountId__c=callouts.DevAccountId__c,AuthenticationURL__c=callouts.DevAuthURL__c,EndPointURL__c=callouts.DevEndpointURL__c,UserPassword__c=callouts.DevPassword__c,UserName__c=callouts.DevUserName__c);
            teamscd = new CalloutData__c (AccountId__c=callouts.DevAccountId__c,AuthenticationURL__c=callouts.DevAuthURL__c,EndPointURL__c=callouts.StageTeamsCreationEndpointURL__c,UserPassword__c=callouts.DevPassword__c,UserName__c=callouts.DevUserName__c);
            System.debug('teamscd.StageTeamsCreationEndpointURL__c----------->>'+teamscd.EndPointURL__c);
            cancelledcd = new CalloutData__c (AccountId__c=callouts.DevAccountId__c,AuthenticationURL__c=callouts.DevAuthURL__c,EndPointURL__c=callouts.StageCancelEndpointURL__c,UserPassword__c=callouts.DevPassword__c,UserName__c=callouts.DevUserName__c);
        }
                
    }
    /**
    private void updateOECEventName(){
        
        List<Order> listOrders = new List<Order>();
        
        for(Order ord:ords){
        
            if(!alreadyProcessedOrds.contains(ord.id))
            {
                System.debug('------------->> In For Loop to process after insert created Records '+trigger.size+'--'+ord.id);
                if(ord.CreatedBy.Name != 'API Integration User') {
                    ord.OEC_Event_Name__c = ord.Name;
                }
                listOrders.add(ord);
                    
                alreadyProcessedOrds.add(ord.Id);    
            }    
                
        }
        if(listOrders.size() > 0)
            update listOrders;
    
    } */
    
    private void dupCheckonOECEventName(List<Order> ordersList){
        if(ordersList.size() > 0) {
            for (Order ord : ordersList) {
                
                Integer existingOrd = [select count() from Order where OEC_Event_Name__c = :ord.OEC_Event_Name__c and Start_Date__c = :ord.Start_Date__c limit 1];
                if (existingOrd > 0) {
                    ord.addError('We cant create a duplicate Order as we have already Order exist with this OEC Event Name/ Event Name and Order Start Date.');
                }
            }
         }
    
    }
    
    
}